/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodiproject;

/**
 *
 * @author VICTUS
 */
public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generateReportSelect = new javax.swing.JComboBox<>();
        editSystemSettingsBtn = new javax.swing.JButton();
        LBBS = new javax.swing.JLabel();
        logOutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        viewCatalogBtn = new javax.swing.JButton();
        changeUserRoleBtn = new javax.swing.JButton();
        makeReportBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        generateReportSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inventory & Circulation", "User Statistics", "Finances" }));
        generateReportSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportSelectActionPerformed(evt);
            }
        });

        editSystemSettingsBtn.setText("EDIT SYSTEM SETTINGS");
        editSystemSettingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSystemSettingsBtnActionPerformed(evt);
            }
        });

        LBBS.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBBS.setForeground(java.awt.Color.black);
        LBBS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBBS.setText("ADMIN DASHBOARD");

        logOutBtn.setText("LOG OUT");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oodiproject/digital-library.png"))); // NOI18N

        viewCatalogBtn.setText("VIEW CATALOG");
        viewCatalogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCatalogBtnActionPerformed(evt);
            }
        });

        changeUserRoleBtn.setText("CHANGE USER'S ROLE");
        changeUserRoleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeUserRoleBtnActionPerformed(evt);
            }
        });

        makeReportBtn.setText("MAKE REPORT");
        makeReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeReportBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBBS, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutBtn)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changeUserRoleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editSystemSettingsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(generateReportSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(makeReportBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(viewCatalogBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(logOutBtn)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LBBS, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(viewCatalogBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editSystemSettingsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changeUserRoleBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(generateReportSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(makeReportBtn))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editSystemSettingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSystemSettingsBtnActionPerformed
        new EditSystemSettingsFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editSystemSettingsBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        LoginFrame loginScreen = new LoginFrame();
        loginScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void viewCatalogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCatalogBtnActionPerformed
        CatalogFrame catalogscreen = new CatalogFrame();
        catalogscreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewCatalogBtnActionPerformed

    private void changeUserRoleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeUserRoleBtnActionPerformed
        new ManageUserRolesFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_changeUserRoleBtnActionPerformed

    private void makeReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeReportBtnActionPerformed
        String selectedReport = generateReportSelect.getSelectedItem().toString();
        StringBuilder reportBuilder = new StringBuilder();
        boolean hasData = false;

        if (selectedReport.equals("Inventory & Circulation")) {
            java.util.ArrayList<Book> booksList = LibraryBookBorrowingSystem.globalCatalog.getBooks();
        
            if (!booksList.isEmpty()) {
                hasData = true;
                reportBuilder.append("=========================================\n");
                reportBuilder.append("    INVENTORY & CIRCULATION REPORT LOG   \n");
                reportBuilder.append("=========================================\n\n");
                reportBuilder.append(String.format("%-10s %-30s %-20s %-12s %-12s\n", "Book ID", "Title", "Author", "Status", "Condition"));
                reportBuilder.append("------------------------------------------------------------------------------------------------------\n");
            
            for (Book b : booksList) {
                String availability = b.isIsAvailable() ? "Available" : "On Loan";
                reportBuilder.append(String.format("%-10d %-30.28s %-20.18s %-12s %-12s\n", 
                        b.getBookID(), b.getTitle(), b.getAuthor(), availability, b.getBookCondition()));
            }
        }
        
        } else if (selectedReport.equals("User Statistics")) {
            java.util.ArrayList<User> usersList = LibraryBookBorrowingSystem.userDatabase;
        
            if (!usersList.isEmpty()) {
                hasData = true;
                reportBuilder.append("=========================================\n");
                reportBuilder.append("    ACTIVE USER METRICS PROFILE REPORT   \n");
                reportBuilder.append("=========================================\n\n");
                reportBuilder.append("Total Registered Accounts: ").append(usersList.size()).append("\n\n");
                reportBuilder.append(String.format("%-10s %-20s %-15s\n", "User ID", "Username", "Account Type"));
                reportBuilder.append("---------------------------------------------------------\n");
            
                for (User u : usersList) {
                    reportBuilder.append(String.format("%-10d %-20s %-15s\n", 
                            u.getUserID(), u.getUsername(), u.getClass().getSimpleName(), u.getPassword()));
                }
            }
        
        } else if (selectedReport.equals("Finances")) {
            Finances finances = LibraryBookBorrowingSystem.globalFinances;
        
            if (finances.getRevenue() != 0 || finances.getExpenditure() != 0) {
                hasData = true;
                double netMargin = finances.getRevenue() - finances.getExpenditure();
            
                reportBuilder.append("=========================================\n");
                reportBuilder.append("      FINANCIAL ANALYSIS REPORT LOG      \n");
                reportBuilder.append("=========================================\n\n");
                reportBuilder.append(String.format("Tracked Total Gross Revenue:   RM %,.2f\n", finances.getRevenue()));
                reportBuilder.append(String.format("Tracked Operating Expenditure: RM %,.2f\n", finances.getExpenditure()));
                reportBuilder.append("-----------------------------------------\n");
                reportBuilder.append(String.format("Net Operating Margin Summary:  RM %,.2f\n", netMargin));
            }
        }

        if (!hasData) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "No data found for the system category selection: " + selectedReport, 
                    "System Operational Warning", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            javax.swing.JTextArea txtArea = new javax.swing.JTextArea(18, 55);
            txtArea.setText(reportBuilder.toString());
            txtArea.setFont(new java.awt.Font("Courier New", java.awt.Font.PLAIN, 12)); // Forces fixed alignment columns
            txtArea.setEditable(false);
            txtArea.setCaretPosition(0); // Anchors scrolling context to the top initial line
        
            javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(txtArea);
        
            javax.swing.JOptionPane.showMessageDialog(this, 
                    scrollPane, 
                    "Generated Report: " + selectedReport, 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_makeReportBtnActionPerformed

    private void generateReportSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generateReportSelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBBS;
    private javax.swing.JButton changeUserRoleBtn;
    private javax.swing.JButton editSystemSettingsBtn;
    private javax.swing.JComboBox<String> generateReportSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton makeReportBtn;
    private javax.swing.JButton viewCatalogBtn;
    // End of variables declaration//GEN-END:variables
}
