/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodiproject;


import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author VICTUS
 */
public class BorrowBookFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BorrowBookFrame.class.getName());

    private User loggedInOperator;
    private Patron targetPatron;
    private ArrayList<Book> displayedBooks;
    /**
     * Creates new form BorrowBookFrame
     */
    public BorrowBookFrame() {
        initComponents();
        this.displayedBooks = new ArrayList<>();
        
        this.loggedInOperator = LibraryBookBorrowingSystem.loggedInUser;
        if (this.loggedInOperator instanceof Patron) {
            this.targetPatron = (Patron) this.loggedInOperator;
        }
        
        configureUserAccess();
        populateBookList();
    }
    
    public BorrowBookFrame(User operator, Patron patron) {
        initComponents();
        this.loggedInOperator = operator;
        this.targetPatron = patron;
        this.displayedBooks = new ArrayList<>();

        configureUserAccess();
        populateBookList();
    }

    private void configureUserAccess() {
        if (loggedInOperator instanceof Patron) {
            targetPatron = (Patron) loggedInOperator;
        
            txtPatronID.setVisible(false);
            lblPatronPrompt.setVisible(false);
        
        } else if (loggedInOperator instanceof Librarian) {
            txtPatronID.setVisible(true);
            lblPatronPrompt.setVisible(true);
            txtPatronID.setEditable(true); 
        }
    }
    
    private void populateBookList() {
        DefaultListModel<String> listModel = new DefaultListModel<>();
        displayedBooks.clear();

        ArrayList<Book> catalog = LibraryBookBorrowingSystem.globalCatalog.getBooks();

        for (Book b : catalog) {
            String availability = b.isIsAvailable() ? "Available" : "Checked Out";
            listModel.addElement(b.getTitle() + " [ID: " + b.getBookID() + "] — (" + availability + ")");
            displayedBooks.add(b);
        }

        lstBooks.setModel(listModel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPatronPrompt = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnBorrow = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtPatronID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstBooks = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPatronPrompt.setText("Target Patron ID:");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitle.setText("BORROW NEW BOOK");

        btnBorrow.setText("CONFIRM");
        btnBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrowActionPerformed(evt);
            }
        });

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtPatronID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatronIDActionPerformed(evt);
            }
        });

        lstBooks.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstBooks);

        jScrollPane1.setViewportView(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btnBorrow))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPatronPrompt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPatronID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(236, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnBack)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPatronID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatronPrompt))
                .addGap(18, 18, 18)
                .addComponent(btnBorrow)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(lblTitle)
                    .addContainerGap(305, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrowActionPerformed
        if (loggedInOperator instanceof Librarian || loggedInOperator instanceof Admin) {
            try {
                int enteredID = Integer.parseInt(txtPatronID.getText().trim());
                Patron found = null;
                
                for (User u : LibraryBookBorrowingSystem.userDatabase) {
                    if (u instanceof Patron && u.getUserID() == enteredID) {
                        found = (Patron) u;
                        break;
                    }
                }
                
                if (found == null) {
                    JOptionPane.showMessageDialog(this, "Patron account matching ID " + enteredID + " could not be found.", "Invalid Account", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                targetPatron = found;
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Please enter a valid numeric Patron ID.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        int selectedIdx = lstBooks.getSelectedIndex();
        if (selectedIdx == -1) {
            JOptionPane.showMessageDialog(this, "Please choose a book from the list above first.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Book selectedBook = displayedBooks.get(selectedIdx);

        if (!selectedBook.isIsAvailable()) {
            JOptionPane.showMessageDialog(this, "Book Unavailable! \"" + selectedBook.getTitle() + "\" is already loaned out.", "Book Unavailable [E1]", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!(loggedInOperator instanceof Librarian)) {
            
            double outstandingBalance = targetPatron.getCurrentFees() + targetPatron.getBorrowingHistory().calculateUnpaidFines();
            if (outstandingBalance >= LibraryBookBorrowingSystem.globalSettings.getFineThreshold()) {
                JOptionPane.showMessageDialog(this, 
                    "Sorry, you may not perform this action until your fines are cleared.\n" +
                    "Your Balance: RM" + String.format("%.2f", outstandingBalance), 
                    "Action Blocked [E2]", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int activeLoansCount = 0;
            for (Loan l : targetPatron.getBorrowingHistory().getLoans()) {
                if ("Due".equalsIgnoreCase(l.getLoanStatus()) || "Overdue".equalsIgnoreCase(l.getLoanStatus())) {
                    activeLoansCount++;
                }
            }
            if (activeLoansCount >= LibraryBookBorrowingSystem.globalSettings.getMaxLoanLimit()) {
                JOptionPane.showMessageDialog(this, "Loan Limit Exceeded! You have already checked out your maximum allowed limit of " + activeLoansCount + " books.", "Quota Limit Hit [E5]", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        selectedBook.setIsAvailable(false);
        Loan newLoanItem = new Loan(selectedBook);
        targetPatron.getBorrowingHistory().addLoanRecord(newLoanItem);
        
        LibraryBookBorrowingSystem.saveData();

        JOptionPane.showMessageDialog(this, "Successfully checked out \"" + selectedBook.getTitle() + "\" for " + targetPatron.getUsername() + "!", "Transaction Approved", JOptionPane.INFORMATION_MESSAGE);
        
        populateBookList();
    }//GEN-LAST:event_btnBorrowActionPerformed

    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        new ManageLoansFrame(loggedInOperator, targetPatron).setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtPatronIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatronIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatronIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BorrowBookFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrowButton;
    private javax.swing.JButton borrowButton1;
    private javax.swing.JButton borrowButton2;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBorrow;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPatronPrompt;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<String> lstBooks;
    private javax.swing.JTextField txtPatronID;
    // End of variables declaration//GEN-END:variables
}
