/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodiproject;

/**
 *
 * @author VICTUS
 */
public class CatalogFrame extends javax.swing.JFrame {
    
    private javax.swing.DefaultListModel<String> listModel;
    private java.util.ArrayList<Book> displayedBooks;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CatalogFrame.class.getName());

    /**
     * Creates new form CatalogFrame
     */
    public CatalogFrame() {
        initComponents();
        listModel = new javax.swing.DefaultListModel<>();
        bookList.setModel(listModel);
    
        displayBooksInGUI(LibraryBookBorrowingSystem.globalCatalog.getBooks());
        
        if (LibraryBookBorrowingSystem.loggedInUser == null) {
        toDashboardBtn.setText("TO MENU");
        } else{
        toDashboardBtn.setText("TO DASHBOARD");
        }
        
        javax.swing.DefaultListModel<String> listModel = new javax.swing.DefaultListModel<>();
    
        for (Book b : LibraryBookBorrowingSystem.globalCatalog.getBooks()) {
            listModel.addElement(b.getTitle() + " [ID: " + b.getBookID() + "]");
        }
    
        bookList.setModel(listModel);
    }

    private void displayBooksInGUI(java.util.ArrayList<Book> booksList) {
        if (listModel == null) {
            listModel = new javax.swing.DefaultListModel<>();
        }
    
        listModel.clear();
    
        this.displayedBooks = new java.util.ArrayList<>(booksList);
    
        for (Book b : booksList) {
            listModel.addElement(b.getTitle() + " by " + b.getAuthor() + " [ID: " + b.getBookID() + "]");
        }
        bookList.setModel(listModel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane3 = new javax.swing.JScrollPane();
        bookList = new javax.swing.JList<>();
        viewDetailsButton = new javax.swing.JToggleButton();
        toDashboardBtn = new javax.swing.JButton();
        searchQuery = new javax.swing.JComboBox<>();
        searchBtn = new javax.swing.JToggleButton();
        searchInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        resetBtn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bookList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "book 1", "book 2", "book 3", "book 4", "book 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(bookList);
        bookList.getAccessibleContext().setAccessibleName("bookList");

        viewDetailsButton.setText("VIEW DETAILS");
        viewDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsButtonActionPerformed(evt);
            }
        });

        toDashboardBtn.setText("TO DASHBOARD");
        toDashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toDashboardBtnActionPerformed(evt);
            }
        });

        searchQuery.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Title", "Author", "Category" }));
        searchQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchQueryActionPerformed(evt);
            }
        });

        searchBtn.setText("SEARCH");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        searchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInputActionPerformed(evt);
            }
        });

        jLabel1.setText("Search for:");

        resetBtn.setSelected(true);
        resetBtn.setText("RESET");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(toDashboardBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 69, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(viewDetailsButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(64, 64, 64))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toDashboardBtn)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchQuery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewDetailsButton)
                    .addComponent(searchBtn)
                    .addComponent(resetBtn))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toDashboardBtnActionPerformed
    User currentUser = LibraryBookBorrowingSystem.loggedInUser;
    
    if (currentUser == null) {
        this.dispose();
        new NewJFrame().setVisible(true);
    }
    else if (currentUser instanceof Admin) {
        this.dispose();
        new AdminDashboard().setVisible(true);
    } else if (currentUser instanceof Librarian) {
        this.dispose();
        new LibrarianDashboard().setVisible(true);
    } else if (currentUser instanceof Patron) {
        this.dispose();
        new PatronDashboard().setVisible(true);
    }
    }//GEN-LAST:event_toDashboardBtnActionPerformed

    private void viewDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsButtonActionPerformed
    int selectedRowIndex = bookList.getSelectedIndex();
    
    if (selectedRowIndex == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Please highlight a book from the list catalog first.", 
                "Selection Required", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    Book chosenBook = LibraryBookBorrowingSystem.globalCatalog.getBooks().get(selectedRowIndex);
    
    javax.swing.JOptionPane.showMessageDialog(this, 
            chosenBook.getDetails(), 
            "Book Profile: " + chosenBook.getTitle(), 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_viewDetailsButtonActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String query = searchInput.getText().trim().toLowerCase();
        String criteria = searchQuery.getSelectedItem().toString();
    
        java.util.ArrayList<Book> matchingResults = new java.util.ArrayList<>();
    
        for (Book b : LibraryBookBorrowingSystem.globalCatalog.getBooks()) {
            if (criteria.equals("Title") && b.getTitle().toLowerCase().contains(query)) {
                matchingResults.add(b);
            } else if (criteria.equals("Author") && b.getAuthor().toLowerCase().contains(query)) {
                matchingResults.add(b);
            } else if (criteria.equals("Category") && b.getGenre().toLowerCase().contains(query)) {
                matchingResults.add(b);
            }
        }
    
        if (matchingResults.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "No books found matching the " + criteria + " query: \"" + searchInput.getText() + "\"", 
                    "Book Not Found", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        
            searchInput.requestFocus();
            searchInput.selectAll();
        } else {
            displayBooksInGUI(matchingResults);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void searchQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchQueryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchQueryActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        searchInput.setText("");
        displayBooksInGUI(LibraryBookBorrowingSystem.globalCatalog.getBooks());
    }//GEN-LAST:event_resetBtnActionPerformed

    private void searchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CatalogFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> bookList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton resetBtn;
    private javax.swing.JToggleButton searchBtn;
    private javax.swing.JTextField searchInput;
    private javax.swing.JComboBox<String> searchQuery;
    private javax.swing.JButton toDashboardBtn;
    private javax.swing.JToggleButton viewDetailsButton;
    // End of variables declaration//GEN-END:variables
}
