/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodiproject;

import java.awt.Color;
import javax.swing.JOptionPane;
/**
 *
 * @author VICTUS
 */
public class EditSystemSettingsFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditSystemSettingsFrame.class.getName());

    /**
     * Creates new form EditSystemSettingsFrame
     */
    public EditSystemSettingsFrame() {
        initComponents();
        loadCurrentConfigurations();
    }
    
    private void loadCurrentConfigurations() {
        SystemSettings settings = LibraryBookBorrowingSystem.globalSettings;
        
        txtMaxLoanLimit.setText(String.valueOf(settings.getMaxLoanLimit()));
        txtMaxRenewals.setText(String.valueOf(settings.getMaxRenewals()));
        txtFineThreshold.setText(String.format("%.2f", settings.getFineThreshold()));
        txtMaxRenewalDuration.setText(String.valueOf(settings.getMaxRenewalDuration()));
        txtFineRate.setText(String.format("%.2f", settings.getFineRate()));
        
        resetFieldBackgrounds();
    }
    
    private void resetFieldBackgrounds() {
        Color defaultWhite = Color.WHITE;
        txtMaxLoanLimit.setBackground(defaultWhite);
        txtMaxRenewals.setBackground(defaultWhite);
        txtFineThreshold.setBackground(defaultWhite);
        txtMaxRenewalDuration.setBackground(defaultWhite);
        txtFineRate.setBackground(defaultWhite);
    }
    
    private void highlightInvalidFields() {
        Color errorRed = new Color(255, 204, 204);
        
        try { 
            if (Integer.parseInt(txtMaxLoanLimit.getText().trim()) < 0) throw new NumberFormatException(); 
        } catch (NumberFormatException e) { txtMaxLoanLimit.setBackground(errorRed); }
        
        try { 
            if (Integer.parseInt(txtMaxRenewals.getText().trim()) < 0) throw new NumberFormatException(); 
        } catch (NumberFormatException e) { txtMaxRenewals.setBackground(errorRed); }
        
        try { 
            if (Double.parseDouble(txtFineThreshold.getText().trim()) < 0) throw new NumberFormatException(); 
        } catch (NumberFormatException e) { txtFineThreshold.setBackground(errorRed); }
        
        try { 
            if (Integer.parseInt(txtMaxRenewalDuration.getText().trim()) < 0) throw new NumberFormatException(); 
        } catch (NumberFormatException e) { txtMaxRenewalDuration.setBackground(errorRed); }
        
        try { 
            if (Double.parseDouble(txtFineRate.getText().trim()) < 0) throw new NumberFormatException(); 
        } catch (NumberFormatException e) { txtFineRate.setBackground(errorRed); }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMaxLoanLimit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMaxRenewals = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFineThreshold = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMaxRenewalDuration = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFineRate = new javax.swing.JTextField();
        saveChangesBtn = new javax.swing.JButton();
        ClearChangesbtn = new javax.swing.JButton();
        Backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeader.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("SYSTEM CONFIGURATION PANEL");

        jLabel1.setText("Max Loan Limit:");

        txtMaxLoanLimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxLoanLimitActionPerformed(evt);
            }
        });

        jLabel2.setText("Max Renewals Allowed:");

        jLabel3.setText("Fine Blockade Threshold (RM):");

        jLabel4.setText("Max Renewal Duration (Days):");

        jLabel5.setText("Daily Fine Accrual Rate (RM):");

        saveChangesBtn.setText("SAVE CHANGES");
        saveChangesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesBtnActionPerformed(evt);
            }
        });

        ClearChangesbtn.setText("CLEAR CHANGES");
        ClearChangesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearChangesbtnActionPerformed(evt);
            }
        });

        Backbtn.setText("BACK");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFineRate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveChangesBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ClearChangesbtn)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFineThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaxRenewalDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtMaxRenewals, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMaxLoanLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Backbtn))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Backbtn)
                    .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaxRenewals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaxRenewalDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFineThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaxLoanLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFineRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveChangesBtn)
                    .addComponent(ClearChangesbtn))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaxLoanLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxLoanLimitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxLoanLimitActionPerformed

    private void saveChangesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesBtnActionPerformed
        resetFieldBackgrounds();
        
        try {
            int maxLoanLimit = Integer.parseInt(txtMaxLoanLimit.getText().trim());
            int maxRenewals = Integer.parseInt(txtMaxRenewals.getText().trim());
            double fineThreshold = Double.parseDouble(txtFineThreshold.getText().trim());
            int maxRenewalDuration = Integer.parseInt(txtMaxRenewalDuration.getText().trim());
            double fineRate = Double.parseDouble(txtFineRate.getText().trim());
            
            if (maxLoanLimit < 0 || maxRenewals < 0 || fineThreshold < 0 || maxRenewalDuration < 0 || fineRate < 0) {
                throw new NumberFormatException("Negative constraints violated");
            }
            
            SystemSettings settings = LibraryBookBorrowingSystem.globalSettings;
            settings.setMaxLoanLimit(maxLoanLimit);
            settings.setMaxRenewals(maxRenewals);
            settings.setFineThreshold(fineThreshold);
            settings.setMaxRenewalDuration(maxRenewalDuration);
            settings.setFineRate(fineRate);
            
            LibraryBookBorrowingSystem.saveData();
            
            JOptionPane.showMessageDialog(this, 
                    "Configuration Changes Successful!\nConfiguration Successfully Updated.", 
                    "Success", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (NumberFormatException e) {
            highlightInvalidFields();
            JOptionPane.showMessageDialog(this, 
                    "Error: Invalid system configurations detected.\nPlease ensure all forms contain positive numeric formats.", 
                    "Invalid Input", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveChangesBtnActionPerformed

    private void ClearChangesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearChangesbtnActionPerformed
        loadCurrentConfigurations();
        JOptionPane.showMessageDialog(this, "Changes Cleared", "Clear Event Triggered", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ClearChangesbtnActionPerformed

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        new AdminDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditSystemSettingsFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JButton ClearChangesbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JButton saveChangesBtn;
    private javax.swing.JTextField txtFineRate;
    private javax.swing.JTextField txtFineThreshold;
    private javax.swing.JTextField txtMaxLoanLimit;
    private javax.swing.JTextField txtMaxRenewalDuration;
    private javax.swing.JTextField txtMaxRenewals;
    // End of variables declaration//GEN-END:variables
}
