/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodiproject;

/**
 *
 * @author muazZ
 */
public class LoanHistoryFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoanHistoryFrame.class.getName());

    private Patron currentPatron = null;
    private final java.time.format.DateTimeFormatter dateFormatter = java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

    /**
     * Creates new form LoanHistoryFrame
     */
    public LoanHistoryFrame() {
        // Retrieve the logged-in Patron session from the central system state
        if (LibraryBookBorrowingSystem.loggedInUser instanceof Patron) {
            this.currentPatron = (Patron) LibraryBookBorrowingSystem.loggedInUser;
        }
        
        initComponents(); // Maintained by NetBeans Design mode
        populateLoanTable();
    }
    
    private void populateLoanTable() {
        if (currentPatron == null || currentPatron.getBorrowingHistory() == null) {
            lblStatusMessage.setText("Status: No active patron profile session detected.");
            return;
        }

        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblLoanHistory.getModel();
        model.setRowCount(0); // Clear any dummy testing rows

        java.util.List<Loan> loansList = currentPatron.getBorrowingHistory().getLoans();
        
        if (loansList.isEmpty()) {
            lblStatusMessage.setText("Status: Clear. You have no recorded transactions.");
            return;
        }

        // Loop through all records retrieved from the history backend engine
        for (Loan loan : loansList) {
            // Check getBorrowedBook() matching the method defined in Loan.java
            String bookTitle = (loan.getBorrowedBook() != null) ? loan.getBorrowedBook().getTitle() : "Unknown Title";
            String bookId = (loan.getBorrowedBook() != null) ? String.valueOf(loan.getBorrowedBook().getBookID()) : "N/A";
            
            String issueDateStr = (loan.getDateOfLoan() != null) ? loan.getDateOfLoan().format(dateFormatter) : "N/A";
            String dueDateStr = (loan.getDueDate() != null) ? loan.getDueDate().format(dateFormatter) : "N/A";
            
            Object[] rowData = {
                bookId,
                bookTitle,
                issueDateStr,
                dueDateStr,
                loan.getCurrentRenewalNo(), // Tracks renewals (up to 5 maximum)
                loan.getLoanStatus()         // Displays "Due" or "Overdue"
            };
            model.addRow(rowData);
        }
        
        lblStatusMessage.setText("Status: Successfully loaded " + loansList.size() + " transaction record(s).");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBBS = new javax.swing.JLabel();
        Backbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoanHistory = new javax.swing.JTable();
        lblStatusMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LBBS.setText("BORROWING & LOAN HISTORY");

        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });

        tblLoanHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Book ID", "Book Title", "Issue Date", "Due Date", "Renews", "State"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLoanHistory);

        lblStatusMessage.setText("Status: Ready");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Backbtn)
                        .addGap(95, 95, 95)
                        .addComponent(LBBS))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblStatusMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBBS)
                    .addComponent(Backbtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatusMessage)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        PatronDashboard patrondashboard = new PatronDashboard();
        patrondashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoanHistoryFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JLabel LBBS;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStatusMessage;
    private javax.swing.JTable tblLoanHistory;
    // End of variables declaration//GEN-END:variables
}
