/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodiproject;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author VICTUS
 */
public class ManageUserRolesFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageUserRolesFrame.class.getName());

    private DefaultListModel<String> listModel;
    private ArrayList<User> displayedUsers;
    
    /**
     * Creates new form ManageUserRolesFrame
     */
    public ManageUserRolesFrame() {
        initComponents();
        listModel = new DefaultListModel<>();
        userList.setModel(listModel);
        displayedUsers = new ArrayList<>();
        
        populateUserList();
        
        userList.addListSelectionListener(evt -> {
            if (!evt.getValueIsAdjusting()) {
                int selectedIndex = userList.getSelectedIndex();
                if (selectedIndex != -1) {
                    User u = displayedUsers.get(selectedIndex);
                    if (u instanceof Admin) {
                        roleComboBox.setSelectedItem("Admin");
                    } else if (u instanceof Librarian) {
                        roleComboBox.setSelectedItem("Librarian");
                    } else if (u instanceof Patron) {
                        roleComboBox.setSelectedItem("Patron");
                    }
                }
            }
        });
    }
    
    private void populateUserList() {
        listModel.clear();
        displayedUsers.clear();
        
        for (User u : LibraryBookBorrowingSystem.userDatabase) {
            if (u instanceof Patron) {
                displayedUsers.add(u);
                listModel.addElement("[Patron] ID: " + u.getUserID() + " | Username: " + u.getUsername());
            }
        }
        
        for (User u : LibraryBookBorrowingSystem.userDatabase) {
            if (u instanceof Librarian) {
                displayedUsers.add(u);
                listModel.addElement("[Librarian] ID: " + u.getUserID() + " | Username: " + u.getUsername());
            }
        }
        
        for (User u : LibraryBookBorrowingSystem.userDatabase) {
            if (u instanceof Admin) {
                displayedUsers.add(u);
                listModel.addElement("[Admin] ID: " + u.getUserID() + " | Username: " + u.getUsername());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userList = new javax.swing.JList<>();
        lblRole = new javax.swing.JLabel();
        roleComboBox = new javax.swing.JComboBox<>();
        btnSaveChanges = new javax.swing.JButton();
        btnClearChanges = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitle.setText("MANAGE USER ACCOUNTS");

        userList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(userList);

        lblRole.setText("Assign New Role:");

        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Patron", "Librarian", "Admin" }));

        btnSaveChanges.setText("SAVE CHANGES");
        btnSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangesActionPerformed(evt);
            }
        });

        btnClearChanges.setText("CLEAR CHANGES");
        btnClearChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearChangesActionPerformed(evt);
            }
        });

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblRole)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnSaveChanges)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClearChanges)))
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRole)
                    .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveChanges)
                    .addComponent(btnClearChanges))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnClearChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearChangesActionPerformed
        populateUserList();
        JOptionPane.showMessageDialog(this, "Changes Reverted.", "System Message", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnClearChangesActionPerformed

    private void btnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangesActionPerformed
        int selectedIndex = userList.getSelectedIndex();
        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(this, "Please select a user account to modify.", "Selection Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        User targetUser = displayedUsers.get(selectedIndex);
        String selectedRole = (String) roleComboBox.getSelectedItem();
        String currentRole = targetUser.getClass().getSimpleName();

        if (selectedRole.equals(currentRole)) {
            JOptionPane.showMessageDialog(this, "The user account already possesses the " + currentRole + " role.", "No Action Required", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        User mutatedUser = null;

        if (selectedRole.equals("Patron")) {
            mutatedUser = new Patron(targetUser.getUsername(), targetUser.getPassword(), targetUser.getUserID(), false, 0.0);
        } 
        else if (selectedRole.equals("Librarian")) {
            String office = JOptionPane.showInputDialog(this, "Enter Library Office Room location:", "Staff Profile Assignment", JOptionPane.QUESTION_MESSAGE);
            if (office == null || office.trim().isEmpty()) return;
            
            String libID = JOptionPane.showInputDialog(this, "Enter unique Librarian ID code:", "Staff Profile Assignment", JOptionPane.QUESTION_MESSAGE);
            if (libID == null || libID.trim().isEmpty()) return;
            
            mutatedUser = new Librarian(targetUser.getUsername(), targetUser.getPassword(), targetUser.getUserID(), office, libID, false);
        } 
        else if (selectedRole.equals("Admin")) {
            String office = JOptionPane.showInputDialog(this, "Enter Administrative Office Room location:", "System Admin Assignment", JOptionPane.QUESTION_MESSAGE);
            if (office == null || office.trim().isEmpty()) return;
            
            String adminID = JOptionPane.showInputDialog(this, "Enter custom Administrator ID code:", "System Admin Assignment", JOptionPane.QUESTION_MESSAGE);
            if (adminID == null || adminID.trim().isEmpty()) return;
            
            mutatedUser = new Admin(targetUser.getUsername(), targetUser.getPassword(), targetUser.getUserID(), office, adminID, false);
        }

        if (mutatedUser != null) {
            for (int i = 0; i < LibraryBookBorrowingSystem.userDatabase.size(); i++) {
                if (LibraryBookBorrowingSystem.userDatabase.get(i).getUserID() == targetUser.getUserID()) {
                    LibraryBookBorrowingSystem.userDatabase.set(i, mutatedUser);
                    break;
                }
            }

            LibraryBookBorrowingSystem.saveData();
            
            JOptionPane.showMessageDialog(this, "Accounts Successfully Updated.", "Success", JOptionPane.INFORMATION_MESSAGE);
            populateUserList();
        }
    }//GEN-LAST:event_btnSaveChangesActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new AdminDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageUserRolesFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClearChanges;
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JComboBox<String> roleComboBox;
    private javax.swing.JList<String> userList;
    // End of variables declaration//GEN-END:variables
}
