/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodiproject;

/**
 *
 * @author muazZ
 */
public class ManageLoansFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageLoansFrame.class.getName());

    
    private User loggedInOperator;
    private Patron targetPatron;
    /**
     * Creates new form ManageLoansFrame
     */
    
    public ManageLoansFrame() {
        initComponents();
        this.loggedInOperator = LibraryBookBorrowingSystem.loggedInUser;
        if (this.loggedInOperator instanceof Patron) {
            this.targetPatron = (Patron) this.loggedInOperator;
        }
    }
    
    public ManageLoansFrame(User operator, Patron patron) {
        initComponents();
        this.loggedInOperator = operator;
        this.targetPatron = patron;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BorrowBooksbtn = new javax.swing.JButton();
        RenewBookbtn = new javax.swing.JButton();
        ReturnBooksbtn = new javax.swing.JButton();
        Backbtn = new javax.swing.JButton();

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oodiproject/digital-library.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(488, 344));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("MANAGE LOANS");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oodiproject/digital-library.png"))); // NOI18N

        BorrowBooksbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BorrowBooksbtn.setText("Borrow Books");
        BorrowBooksbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrowBooksbtnActionPerformed(evt);
            }
        });

        RenewBookbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RenewBookbtn.setText("Renew Books");
        RenewBookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RenewBookbtnActionPerformed(evt);
            }
        });

        ReturnBooksbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ReturnBooksbtn.setText("Return Books");
        ReturnBooksbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBooksbtnActionPerformed(evt);
            }
        });

        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BorrowBooksbtn)
                            .addComponent(RenewBookbtn)
                            .addComponent(ReturnBooksbtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Backbtn))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(BorrowBooksbtn)
                        .addGap(18, 18, 18)
                        .addComponent(RenewBookbtn)
                        .addGap(18, 18, 18)
                        .addComponent(ReturnBooksbtn)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BorrowBooksbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrowBooksbtnActionPerformed
        this.dispose();
        new BorrowBookFrame(loggedInOperator, targetPatron).setVisible(true);
    }//GEN-LAST:event_BorrowBooksbtnActionPerformed

    private void RenewBookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RenewBookbtnActionPerformed
        this.dispose();
        new RenewBookFrame(loggedInOperator, targetPatron).setVisible(true);
    }//GEN-LAST:event_RenewBookbtnActionPerformed

    private void ReturnBooksbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBooksbtnActionPerformed
        this.dispose();
        new ReturnBookFrame(loggedInOperator, targetPatron).setVisible(true);
    }//GEN-LAST:event_ReturnBooksbtnActionPerformed

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        this.dispose();
        if (loggedInOperator instanceof Librarian || loggedInOperator instanceof Admin) {
            new LibrarianDashboard().setVisible(true);
        } else {
            new PatronDashboard().setVisible(true);
        }
    }//GEN-LAST:event_BackbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageLoansFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JButton BorrowBooksbtn;
    private javax.swing.JButton RenewBookbtn;
    private javax.swing.JButton ReturnBooksbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
