/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodiproject;

/**
 *
 * @author muazZ
 */
public class PayFeesFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PayFeesFrame.class.getName());
    
    private Patron currentPatron = null;
    private double calculatedPaymentFee = 0.0;

    public PayFeesFrame() {
        if (LibraryBookBorrowingSystem.loggedInUser instanceof Patron) {
            this.currentPatron = (Patron) LibraryBookBorrowingSystem.loggedInUser;
        }
        
        initComponents();
        updateFeeLabels();
    }
    
    private void updateFeeLabels() {
        if (currentPatron != null) {
            lblOutstandingFees.setText(String.format("RM%.2f", currentPatron.getCurrentFees()));
        } else {
            lblOutstandingFees.setText("RM0.00");
        }
        lblPaidFees.setText("RM0.00"); 
        TotalPaymentFee.setText(String.format("Total Payment Fee: RM%.2f", calculatedPaymentFee));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        outstandingfee1 = new javax.swing.JLabel();
        LBBS = new javax.swing.JLabel();
        outstandingfee = new javax.swing.JLabel();
        paidfee = new javax.swing.JLabel();
        lblPaidFees = new javax.swing.JLabel();
        lblOutstandingFees = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        txtPayAmount = new javax.swing.JTextField();
        CalculateFee = new javax.swing.JButton();
        TotalPaymentFee = new javax.swing.JLabel();
        PaymentMethodSelect = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        ConfirmPaymentbtn = new javax.swing.JButton();
        Backbtn = new javax.swing.JButton();

        outstandingfee1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        outstandingfee1.setText("Outstanding Fees:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LBBS.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBBS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBBS.setText("PAY FINES");

        outstandingfee.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        outstandingfee.setText("Outstanding Fees:");

        paidfee.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        paidfee.setText("Paid Fees:");

        lblPaidFees.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPaidFees.setText("RM00.00");

        lblOutstandingFees.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblOutstandingFees.setText("RM00.00");

        amount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        amount.setText("Enter Payment Amount:");

        txtPayAmount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPayAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPayAmountActionPerformed(evt);
            }
        });

        CalculateFee.setText("Calculate");
        CalculateFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateFeeActionPerformed(evt);
            }
        });

        TotalPaymentFee.setText("Total Payment Fee: RM0.00");

        PaymentMethodSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Online Banking", "E-Wallet", "Debit/Credit Card", "PayPal" }));
        PaymentMethodSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentMethodSelectActionPerformed(evt);
            }
        });

        jLabel2.setText("Choose Payment Method:");

        ConfirmPaymentbtn.setText("Confirm");
        ConfirmPaymentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPaymentbtnActionPerformed(evt);
            }
        });

        Backbtn.setText("BACK");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(417, 417, 417)
                        .addComponent(ConfirmPaymentbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(outstandingfee)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblOutstandingFees, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(paidfee, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPaidFees, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PaymentMethodSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(amount)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPayAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CalculateFee))
                                    .addComponent(TotalPaymentFee, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(LBBS, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(Backbtn)
                .addGap(18, 18, 18)
                .addComponent(LBBS, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaidFees)
                    .addComponent(paidfee, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOutstandingFees)
                    .addComponent(outstandingfee, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPayAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CalculateFee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalPaymentFee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PaymentMethodSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(ConfirmPaymentbtn)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPayAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPayAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPayAmountActionPerformed

    private void PaymentMethodSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentMethodSelectActionPerformed
         String PaymentMethod = PaymentMethodSelect.getSelectedItem().toString();
    }//GEN-LAST:event_PaymentMethodSelectActionPerformed

    private void ConfirmPaymentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPaymentbtnActionPerformed
        if (currentPatron == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No active patron profile found.", "System Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (calculatedPaymentFee <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please insert an amount and click 'Calculate' before confirming your payment.", "Action Required", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String chosenMethod = PaymentMethodSelect.getSelectedItem().toString();
        
        // Track fees before processing payment
        double initialFees = currentPatron.getCurrentFees();
        
        // Execute the exact backend payment calculation method
        currentPatron.payFees(calculatedPaymentFee);
        
        // Calculate the difference to determine the exact payment made
        double finalFees = currentPatron.getCurrentFees();
        double actualPaidAmount = initialFees - finalFees;
        
        // Update the global core finances record directly without changing the main file
        LibraryBookBorrowingSystem.globalFinances.setRevenue(
            LibraryBookBorrowingSystem.globalFinances.getRevenue() + actualPaidAmount
        );
        
        // Save the updated database to storagefile.dat immediately
        LibraryBookBorrowingSystem.saveData();
        
        // Show success alert confirmation popup
        String successMessage = String.format("Payment of RM%.2f via %s was successful!", actualPaidAmount, chosenMethod);
        javax.swing.JOptionPane.showMessageDialog(this, successMessage, "Payment Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        // Reset local transaction inputs
        calculatedPaymentFee = 0.0;
        txtPayAmount.setText("");
        updateFeeLabels();
        
        // Close the payment window and redirect to the dashboard view
        PatronDashboard patrondashboard = new PatronDashboard();
        patrondashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ConfirmPaymentbtnActionPerformed

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        PatronDashboard patrondashboard = new PatronDashboard();
        patrondashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackbtnActionPerformed

    private void CalculateFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateFeeActionPerformed
        if (currentPatron == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No active patron profile found. Please login first.", "System Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            String textAmount = txtPayAmount.getText().trim();
            if (textAmount.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please enter a payment amount.", "Input Error", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            double inputAmount = Double.parseDouble(textAmount);
            
            if (inputAmount <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Payment amount must be greater than RM0.00.", "Input Error", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // Check against the user's actual outstanding balance
            if (inputAmount > currentPatron.getCurrentFees()) {
                javax.swing.JOptionPane.showMessageDialog(this, "You cannot pay more than your outstanding fee balance.", "Input Error", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            calculatedPaymentFee = inputAmount;
            updateFeeLabels();
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid numeric amount (e.g., 10.50).", "Format Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CalculateFeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PayFeesFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JButton CalculateFee;
    private javax.swing.JButton ConfirmPaymentbtn;
    private javax.swing.JLabel LBBS;
    private javax.swing.JComboBox<String> PaymentMethodSelect;
    private javax.swing.JLabel TotalPaymentFee;
    private javax.swing.JLabel amount;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblOutstandingFees;
    private javax.swing.JLabel lblPaidFees;
    private javax.swing.JLabel outstandingfee;
    private javax.swing.JLabel outstandingfee1;
    private javax.swing.JLabel paidfee;
    private javax.swing.JTextField txtPayAmount;
    // End of variables declaration//GEN-END:variables
}
