/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodiproject;

/**
 *
 * @author muazZ
 */
public class PayFeesFrame extends javax.swing.JFrame {
    
    private Patron currentPatron = null;
    private double calculatedPaymentFee = 0.0;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PayFeesFrame.class.getName());

    public PayFeesFrame() {
        System.out.println("[DEBUG]: Global loggedInUser is: " + LibraryBookBorrowingSystem.loggedInUser);
        
        if (LibraryBookBorrowingSystem.loggedInUser instanceof Patron) {
            this.currentPatron = (Patron) LibraryBookBorrowingSystem.loggedInUser;
            System.out.println("[DEBUG]: Successfully detected Patron! Username: " + this.currentPatron.getUsername());
            System.out.println("[DEBUG]: Successfully detected Patron! Password: " + this.currentPatron.getPassword());
            System.out.println("[DEBUG]: Successfully detected Patron! Current Fees: " + this.currentPatron.getCurrentFees());
        } else {
            System.out.println("[DEBUG]: WARNING! loggedInUser is either null or not an instance of Patron.");
        }
        
        initComponents();
        updateFeeLabels();
    }
    
    private void updateFeeLabels() {
        if (currentPatron != null) {
        if (currentPatron.getBorrowingHistory() != null) {
            double historyFines = currentPatron.getBorrowingHistory().calculateUnpaidFines();
            if (historyFines > 0 && currentPatron.getCurrentFees() == 0.0) {
                currentPatron.setCurrentFees(historyFines);
            }
        }
        lblOutstandingFees.setText(String.format("RM%.2f", currentPatron.getCurrentFees()));
    } else {
        lblOutstandingFees.setText("RM0.00");
    } 
    TotalPaymentFee.setText(String.format("Total Payment Fee: RM%.2f", calculatedPaymentFee));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBBS = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblOutstandingFees = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPayAmount = new javax.swing.JTextField();
        CalculateFee = new javax.swing.JButton();
        TotalPaymentFee = new javax.swing.JLabel();
        jlabel69 = new javax.swing.JLabel();
        PaymentMethodSelect = new javax.swing.JComboBox<>();
        ConfirmPaymentbtn = new javax.swing.JButton();
        Backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LBBS.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBBS.setText("PAY FINES AND SYSTEM FEES");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Outstanding Fees:");

        lblOutstandingFees.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblOutstandingFees.setText("RM0.00");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Enter Payment Amount:");

        txtPayAmount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPayAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPayAmountActionPerformed(evt);
            }
        });

        CalculateFee.setText("Calculate");
        CalculateFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateFeeActionPerformed(evt);
            }
        });

        TotalPaymentFee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TotalPaymentFee.setText("Total Payment Fee: RM0.00");

        jlabel69.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlabel69.setText("Choose Payment Method:");

        PaymentMethodSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Online Banking", "E-Wallet", "Debit/Credit Card", "PayPal" }));
        PaymentMethodSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentMethodSelectActionPerformed(evt);
            }
        });

        ConfirmPaymentbtn.setText("Confirm Payment");
        ConfirmPaymentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPaymentbtnActionPerformed(evt);
            }
        });

        Backbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Backbtn.setText("BACK TO DASHBOARD");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ConfirmPaymentbtn)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(LBBS)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblOutstandingFees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlabel69, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TotalPaymentFee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPayAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CalculateFee))
                            .addComponent(PaymentMethodSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Backbtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(Backbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LBBS)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblOutstandingFees))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPayAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CalculateFee))
                .addGap(18, 18, 18)
                .addComponent(TotalPaymentFee)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel69)
                    .addComponent(PaymentMethodSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ConfirmPaymentbtn)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPayAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPayAmountActionPerformed
        
    }//GEN-LAST:event_txtPayAmountActionPerformed

    private void CalculateFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateFeeActionPerformed
        String textInput = txtPayAmount.getText().trim();
        if (textInput.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in a valid numeric amount to calculate.", "Input Missing", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            double parsedAmount = Double.parseDouble(textInput);
            if (parsedAmount <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "The target payment amount must be greater than RM0.00", "Invalid Amount", javax.swing.JOptionPane.ERROR_MESSAGE);
                calculatedPaymentFee = 0.0;
            } else {
                calculatedPaymentFee = parsedAmount;
            }
            updateFeeLabels();
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Format Error: Please insert a valid numeric value (e.g., 10.50)", "Numeric Parsing Failed", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CalculateFeeActionPerformed

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        PatronDashboard dashboard = new PatronDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackbtnActionPerformed

    private void ConfirmPaymentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPaymentbtnActionPerformed
        if (currentPatron == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: No active patron user account matched.", "Session Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (calculatedPaymentFee <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid amount and click 'Calculate' first before finalizing.", "Payment Uncalculated", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        String selectedMethod = (String) PaymentMethodSelect.getSelectedItem();
        int answer = javax.swing.JOptionPane.showConfirmDialog(this, 
                String.format("Confirm processing payment of RM%.2f via %s?", calculatedPaymentFee, selectedMethod),
                "Execute Transaction", javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (answer == javax.swing.JOptionPane.YES_OPTION) {
            double priorFee = currentPatron.getCurrentFees();
            currentPatron.payFees(calculatedPaymentFee);
            
            if (calculatedPaymentFee >= priorFee) {
                double change = calculatedPaymentFee - priorFee;
                javax.swing.JOptionPane.showMessageDialog(this, 
                        String.format("Fees paid successfully!\nCleared System Balance.\nYour Change: RM%.2f", change), 
                        "Transaction Approved", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                        String.format("Partial balance payment recorded.\nRemaining balance: RM%.2f", currentPatron.getCurrentFees()), 
                        "Transaction Approved", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            
            // Sync mutations across data models and flush storage cache safely
            LibraryBookBorrowingSystem.saveData();
            
            // Refresh components and input text fields
            calculatedPaymentFee = 0.0;
            txtPayAmount.setText("");
            updateFeeLabels();
        }
    }//GEN-LAST:event_ConfirmPaymentbtnActionPerformed

    private void PaymentMethodSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentMethodSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaymentMethodSelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PayFeesFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JButton CalculateFee;
    private javax.swing.JButton ConfirmPaymentbtn;
    private javax.swing.JLabel LBBS;
    private javax.swing.JComboBox<String> PaymentMethodSelect;
    private javax.swing.JLabel TotalPaymentFee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlabel69;
    private javax.swing.JLabel lblOutstandingFees;
    private javax.swing.JTextField txtPayAmount;
    // End of variables declaration//GEN-END:variables
}
