/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodiproject;

import java.util.List;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author VICTUS
 */
public class ReturnBookFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReturnBookFrame.class.getName());

    private User loggedInOperator;
    private Patron targetPatron;
    /**
     * Creates new form ReturnBookFrame
     */
    public ReturnBookFrame() {
        initComponents();
        this.loggedInOperator = LibraryBookBorrowingSystem.loggedInUser;
        initializeSession();
    }
    
    public ReturnBookFrame(User operator, Patron patron) {
        initComponents();
        this.loggedInOperator = operator;
        this.targetPatron = patron;
        initializeSession();
    }
    
    private void initializeSession() {
        if (this.loggedInOperator == null) {
            this.loggedInOperator = LibraryBookBorrowingSystem.loggedInUser;
        }

        if (this.targetPatron == null && (loggedInOperator instanceof Librarian || loggedInOperator instanceof Admin)) {
            promptForTargetPatron();
        } else if (loggedInOperator instanceof Patron) {
            this.targetPatron = (Patron) loggedInOperator;
        }

        if (targetPatron != null) {
            txtPatronInfo.setText(targetPatron.getUsername() + " [ID: " + targetPatron.getUserID() + "]");
            populateBorrowedBooksList();
        } else {
            this.dispose();
            new ManageLoansFrame(loggedInOperator, null).setVisible(true);
        }
    }
    
    private void promptForTargetPatron() {
        String input = JOptionPane.showInputDialog(this, 
                "Enter target Patron Account User ID:", 
                "Librarian Lookup Verification", 
                JOptionPane.QUESTION_MESSAGE);
                
        if (input == null || input.trim().isEmpty()) {
            return;
        }

        try {
            int targetPatronID = Integer.parseInt(input.trim());
            for (User u : LibraryBookBorrowingSystem.userDatabase) {
                if (u instanceof Patron && u.getUserID() == targetPatronID) {
                    this.targetPatron = (Patron) u;
                    break;
                }
            }
            if (this.targetPatron == null) {
                JOptionPane.showMessageDialog(this, 
                        "No registered profile records match User ID: " + targetPatronID, 
                        "System Error", 
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid ID Format. Please enter numeric digits.", "Format Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void populateBorrowedBooksList() {
        DefaultListModel<String> listModel = new DefaultListModel<>();
        if (targetPatron != null) {
            List<Loan> masterLog = targetPatron.getBorrowingHistory().getLoans();
            for (Loan l : masterLog) {
                Book b = l.getBorrowedBook();
                listModel.addElement(b.getTitle() + " [ID: " + b.getBookID() + "] - Due: " + l.getDueDate().toLocalDate());
            }
        }
        lstBorrowedBooks.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPatronInfo = new javax.swing.JLabel();
        txtPatronInfo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstBorrowedBooks = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        cmbCondition = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        btnConfirmReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitle.setText("RETURN BORROWED BOOKS");

        lblPatronInfo.setText("Active Patron:");

        txtPatronInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatronInfoActionPerformed(evt);
            }
        });

        lstBorrowedBooks.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstBorrowedBooks);

        jLabel1.setText("Select Book Condition:");

        cmbCondition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Good", "Damaged", "Lost" }));

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnConfirmReturn.setText("CONFIRM");
        btnConfirmReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 99, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPatronInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPatronInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)
                        .addGap(20, 20, 20))))
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(btnConfirmReturn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatronInfo)
                    .addComponent(txtPatronInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnConfirmReturn)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmReturnActionPerformed
        int selectedIndex = lstBorrowedBooks.getSelectedIndex();
        
        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(this, "Please select a borrowed book from the listing to return.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        List<Loan> activeLoans = targetPatron.getBorrowingHistory().getLoans();
        Loan selectedLoan = activeLoans.get(selectedIndex);
        Book borrowedBook = selectedLoan.getBorrowedBook();
        String selectedCondition = (String) cmbCondition.getSelectedItem();

        borrowedBook.updateCondition(selectedCondition);
        borrowedBook.updateStatus(true);

        double transactionFine = selectedLoan.calculateFine();
        
        if ("Lost".equalsIgnoreCase(selectedCondition)) {
            transactionFine += 50.00; 
        }

        if (transactionFine > 0) {
            targetPatron.setCurrentFees(targetPatron.getCurrentFees() + transactionFine);
            JOptionPane.showMessageDialog(this, 
                "[FEES ASSESSED]: An automated tracking fine of RM" + String.format("%.2f", transactionFine) + 
                "\nhas been assessed and compiled into this profile's outstanding bills.", 
                "Account Fees Modification Notification", 
                JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, 
                "[RETURN SUCCESSFUL]: Book returned on schedule in satisfactory condition.\nNo system penalties incurred.", 
                "Transaction Confirmed", 
                JOptionPane.INFORMATION_MESSAGE);
        }

        activeLoans.remove(selectedIndex);

        LibraryBookBorrowingSystem.saveData();

        populateBorrowedBooksList();
    }//GEN-LAST:event_btnConfirmReturnActionPerformed

    private void txtPatronInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatronInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatronInfoActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        new ManageLoansFrame(loggedInOperator, targetPatron).setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReturnBookFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirmReturn;
    private javax.swing.JComboBox<String> cmbCondition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPatronInfo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<String> lstBorrowedBooks;
    private javax.swing.JTextField txtPatronInfo;
    // End of variables declaration//GEN-END:variables
}
