/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodiproject;

/**
 *
 * @author VICTUS
 */
public class SignupFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignupFrame.class.getName());

    /**
     * Creates new form SignupFrame
     */
    public SignupFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBBS1 = new javax.swing.JLabel();
        LBBS2 = new javax.swing.JLabel();
        LBBS3 = new javax.swing.JLabel();
        toLoginButton = new javax.swing.JButton();
        LBBS = new javax.swing.JLabel();
        menuButton = new javax.swing.JButton();
        signupButton = new javax.swing.JButton();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        LBBS4 = new javax.swing.JLabel();
        LBBS5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LBBS1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LBBS1.setForeground(java.awt.Color.black);
        LBBS1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBBS1.setText("Password:");

        LBBS2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LBBS2.setForeground(java.awt.Color.black);
        LBBS2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBBS2.setText("Username:");

        LBBS3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LBBS3.setForeground(java.awt.Color.black);
        LBBS3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBBS3.setText("Already have an account?");

        toLoginButton.setText("LOG IN");
        toLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toLoginButtonActionPerformed(evt);
            }
        });

        LBBS.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBBS.setForeground(java.awt.Color.black);
        LBBS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBBS.setText("USER SIGNUP PAGE");

        menuButton.setText("BACK TO MENU");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        signupButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        signupButton.setText("SIGN UP");
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        LBBS4.setForeground(java.awt.Color.black);
        LBBS4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBBS4.setText("Username must have at least 1 uppercase letter,");

        LBBS5.setForeground(java.awt.Color.black);
        LBBS5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBBS5.setText("Password must have at least 8 characters");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(menuButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(LBBS2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(LBBS1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(signupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passwordField))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBBS3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toLoginButton)))))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(LBBS5, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(LBBS4, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(94, 94, 94))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(LBBS, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(151, 151, 151)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBBS, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(LBBS4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBBS5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBBS2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBBS1)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(signupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBBS3)
                    .addComponent(toLoginButton))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toLoginButtonActionPerformed
        LoginFrame loginScreen = new LoginFrame();
        loginScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_toLoginButtonActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        NewJFrame homescreen = new NewJFrame();
        homescreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuButtonActionPerformed

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        String usernameInput = usernameField.getText().trim();
        String passwordInput = new String(passwordField.getPassword());
    
        boolean matchesUsernameConstraint = usernameInput.matches(".*[A-Z].*");
        boolean matchesPasswordConstraint = passwordInput.length() >= 8;
    
        if (!matchesUsernameConstraint || !matchesPasswordConstraint) {
            String complianceMessage = "Must meet constraints:\n";
            if (!matchesUsernameConstraint) {
                complianceMessage += "- Username must have at least 1 Uppercase Letter.\n";
            }
            if (!matchesPasswordConstraint) {
                complianceMessage += "- Password must have at least 8 characters.\n";
            }
        
            javax.swing.JOptionPane.showMessageDialog(this, 
                    complianceMessage, 
                    "Registration Constraint Error", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
    
        int generatedID = 1000 + LibraryBookBorrowingSystem.userDatabase.size(); 
    
        Patron newlyRegisteredPatron = new Patron(usernameInput, passwordInput, generatedID, false, 0.0);
    
        LibraryBookBorrowingSystem.userDatabase.add(newlyRegisteredPatron);
        LibraryBookBorrowingSystem.saveData();
    
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Signed Up Successfully", 
                "Profile Configured", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
    
        this.dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_signupButtonActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignupFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBBS;
    private javax.swing.JLabel LBBS1;
    private javax.swing.JLabel LBBS2;
    private javax.swing.JLabel LBBS3;
    private javax.swing.JLabel LBBS4;
    private javax.swing.JLabel LBBS5;
    private javax.swing.JButton menuButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton signupButton;
    private javax.swing.JButton toLoginButton;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
